@baseUrl = http://localhost:3000

### 404 Route
get {{baseUrl}}

### Ping Route
get {{baseUrl}}/ping

### Get User
get {{baseUrl}}/users?phone=8898452513
token: uzaru88j5ujnjl3hhqd2

### Create User
post {{baseUrl}}/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "phone": "8898452513",
  "password": "teste123",
  "tosAgreement": true
}

### Update User
put {{baseUrl}}/users
Content-Type: application/json

{
  "lastName": "Smith",
  "phone": "8898452513",
  "password": "teste1234"
}

### Delete User
delete {{baseUrl}}/users?phone=8898452513
Content-Type: application/json
token: 91qhifltkp7dsip9esqi

### Get Token
get {{baseUrl}}/tokens?id=2g4obadif86xprkl38v5

### Create Token
post {{baseUrl}}/tokens
Content-Type: application/json

{
  "phone": "8898452513",
  "password": "teste123"
}

### Update Token
put {{baseUrl}}/tokens
Content-Type: application/json

{
  "id": "2g4obadif86xprkl38v5",
  "extend": true
}

### Delete token
delete {{baseUrl}}/tokens?id=2g4obadif86xprkl38v5

### Get check
get {{baseUrl}}/checks?id=ecmey2ry6dnkj8icizbi
Content-Type: application/json
token: 28wuchmya7e0v0ipez72

### Create check
post {{baseUrl}}/checks
Content-Type: application/json
token: c1qwm49gz8xvwdk9e1xx

{
  "protocol": "http",
  "url": "google.com",
  "method": "get",
  "successCodes": [200, 201],
  "timeoutSeconds": 3
}

### Update check
put {{baseUrl}}/checks?id=ecmey2ry6dnkj8icizbi
Content-Type: application/json
token: 28wuchmya7e0v0ipez72

{
  "id": "ecmey2ry6dnkj8icizbi",
  "protocol": "https",
  "url": "yahoo.com",
  "method": "put",
  "successCodes": [200, 201, 403],
  "timeoutSeconds": 2
}

### Delete check
delete {{baseUrl}}/checks?id=ecmey2ry6dnkj8icizbi
Content-Type: application/json
token: 28wuchmya7e0v0ipez72